#!/bin/sh

# IPv4 only
KINDLE_IP=192.168.15.244

# Enable password override
PASSWORD_OVERRIDE_ENABLED="true"
PASSWORD="kindle"

# Disabling this will enforce private key login
ALLOW_PASSWORD_LOGIN="true"

# SSH port
PORT="22"

# Enable SSH over Wi-Fi
USE_WIFI="true"

# Uncomment to enable faster transfers but higher memory usage
# WINDOW_SIZE="6291456"
